server:
    port: 8080
spring:
    cloud:
        gateway:
            routes:
                -   id: test
                    uri: http://127.0.0.1:8081
                    predicates:
                        - Path=/test/**
encryptor:
    config:
        reactive:
            crypto-config:
                private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKlPT4bCuAmY7vPxJjXnU9hACtV2VfrxvY8tcfuzQJs8ipSoBmKDAPYPlCIAhZDMtartp/gvnVm9iflUk8hwo5Cpfzp7dZ+gGePT5HoT1Fs5AS6+Rq1mf+tfRZY2o6Er5TqBrdhYR8A15P2AYBp/ckfto4zrYFB3WB2woqdwt5jtAgMBAAECgYABSsnUa/ZZRbxbypUxknSOhnKZYsqmMc5yDMqSvVv6s1FqxVuDHfUrFj8EVr+uNWRqNl/H955k+cWB9yDHm1XMOM01iOBevXdWOW2OGeYB/IsPmpwnkK5frjU5FNxWAe96C/7btJLV2YmVo/bcTkYk+6Oyzh//h/SZdHNdJ13vAQJBAO0VSe73QzQ6z0wwcFy+E/G/mLCD+YK4vJRKRadO3EBGXByMxTMF5bxyKbwPRve9TQPaIcKScaC6HT5MI6DQ14ECQQC20as8yEK+PI/qg5HitRb4PVS1QJu/TH/2HC339QoMjmn30SBnF38B4nxN6XgZhLyUpRtnhMUDwxHok/deD1dtAkA0MpS1jTD5pd0QHDYQ5TSE7DcU3emoUz4JtBSD0oQBjrwm+QNNyYWcKNJxejeYwc/cAkGekhl8Vp2rop3RgUmBAkBkw6fYNqDi7cp8/cu44wsoA9XemR+/DtEwu1Ny6bKCPTSXDMMJT2AHj+fnoZk6p3ixjVdPdVSJwEjsojGjvFz5AkEAmoSHxY23ytLrkMggR1c9SQ4O0rZfURLRYTGG2t4EutQzpLmwalye8vvUOKKNWk4GauH085FvFw4iFhVAnRl71A==
                public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCpT0+GwrgJmO7z8SY151PYQArVdlX68b2PLXH7s0CbPIqUqAZigwD2D5QiAIWQzLWq7af4L51ZvYn5VJPIcKOQqX86e3WfoBnj0+R6E9RbOQEuvkatZn/rX0WWNqOhK+U6ga3YWEfANeT9gGAaf3JH7aOM62BQd1gdsKKncLeY7QIDAQAB